import type { Issue } from './types';

export const issues: Issue[] = [
  {
    id: 'ISS-001',
    title: 'Massive Pothole on Elm Street',
    description: 'A very large and dangerous pothole has formed at the intersection of Elm Street and Oak Avenue, right in front of the bakery. It has already caused a flat tire for one car.',
    category: 'Roads',
    severity: 'High',
    location: 'Elm Street & Oak Avenue',
    imageId: 'pothole-1',
    upvotes: 128,
    status: 'In Progress',
    isAnonymous: false,
    author: 'Jane Doe',
    createdAt: '2024-07-20',
    updates: [
        { status: 'Submitted', date: '2024-07-20', description: 'Reported by Jane Doe.' },
        { status: 'Acknowledged', date: '2024-07-21', description: 'Public Works department has acknowledged the issue.' },
        { status: 'In Progress', date: '2024-07-22', description: 'A crew has been dispatched for repairs.' },
        { status: 'Resolved', date: '2024-07-23', description: 'Pothole has been filled.' },
    ]
  },
  {
    id: 'ISS-002',
    title: 'Garbage bins overflowing at City Park',
    description: 'The garbage bins near the main entrance of City Park have been overflowing for three days. It is attracting pests and creating a very unpleasant smell.',
    category: 'Waste Management',
    severity: 'Medium',
    location: 'City Park, Main Entrance',
    imageId: 'waste-1',
    upvotes: 74,
    status: 'Acknowledged',
    isAnonymous: true,
    author: 'Anonymous',
    createdAt: '2024-07-19',
    updates: [
        { status: 'Submitted', date: '2024-07-19', description: 'Reported by a concerned citizen.' },
        { status: 'Acknowledged', date: '2024-07-20', description: 'Sanitation department has scheduled a pickup.' },
        { status: 'In Progress', date: '2024-07-21', description: 'Awaiting crew.' },
        { status: 'Resolved', date: '2024-07-22', description: 'Waste has been cleared.' },
    ]
  },
  {
    id: 'ISS-003',
    title: 'Streetlight out on 5th Avenue',
    description: 'The streetlight at the corner of 5th Avenue and Pine St. is completely out. It\'s a dark corner and feels unsafe at night.',
    category: 'Electricity',
    severity: 'Medium',
    location: '5th Avenue & Pine St.',
    imageId: 'streetlight-1',
    upvotes: 45,
    status: 'Submitted',
    isAnonymous: false,
    author: 'John Smith',
    createdAt: '2024-07-22',
    updates: [
        { status: 'Submitted', date: '2024-07-22', description: 'Reported by John Smith.' },
        { status: 'Acknowledged', date: '2024-07-23', description: 'Issue received by Electrical department.' },
        { status: 'In Progress', date: '2024-07-24', description: 'Awaiting technician.' },
        { status: 'Resolved', date: '2024-07-25', description: 'Bulb replaced.' },
    ]
  },
    {
    id: 'ISS-004',
    title: 'Water pipe leaking for days',
    description: 'There is a steady leak from a water pipe near the Maplewood library. A large puddle has formed and clean water is being wasted.',
    category: 'Water Supply',
    severity: 'High',
    location: 'Maplewood Library',
    imageId: 'water-1',
    upvotes: 210,
    status: 'Resolved',
    isAnonymous: false,
    author: 'Emily White',
    createdAt: '2024-07-15',
    updates: [
        { status: 'Submitted', date: '2024-07-15', description: 'Reported by Emily White.' },
        { status: 'Acknowledged', date: '2024-07-15', description: 'Water department acknowledged.' },
        { status: 'In Progress', date: '2024-07-16', description: 'Repair crew on site.' },
        { status: 'Resolved', date: '2024-07-16', description: 'Pipe has been fixed.' },
    ]
  },
    {
    id: 'ISS-005',
    title: 'Bus stop shelter glass shattered',
    description: 'The glass panel at the bus stop on Central Station Road is shattered and has created a safety hazard with glass on the ground.',
    category: 'Public Transport',
    severity: 'Medium',
    location: 'Central Station Road Bus Stop',
    imageId: 'transport-1',
    upvotes: 33,
    status: 'Acknowledged',
    isAnonymous: true,
    author: 'Anonymous',
    createdAt: '2024-07-21',
    updates: [
        { status: 'Submitted', date: '2024-07-21', description: 'Reported anonymously.' },
        { status: 'Acknowledged', date: '2024-07-22', description: 'Transit authority has been notified.' },
        { status: 'In Progress', date: '2024-07-23', description: 'Cleanup and repair scheduled.' },
        { status: 'Resolved', date: '2024-07-24', description: 'Area cleaned and panel replaced.' },
    ]
  },
];
